//! Internal result surface for hidden-base local recovery.

use std::time::Duration;

use super::super::HiddenBaseRoundTrip;
use super::HiddenBaseLocalRecoveredKey;

pub(super) struct LocalSearchOutput {
    pub(super) sigma_domain_size: usize,
    pub(super) attempts_run: usize,
    pub(super) candidate_evaluations: usize,
    pub(super) replay_event_evaluations: usize,
    pub(super) joint_move_candidate_evaluations: usize,
    pub(super) joint_move_replay_event_evaluations: usize,
    pub(super) joint_move_total_budget_exhausted: bool,
    pub(super) joint_moves_accepted: usize,
    pub(super) joint_move_letter_pairs_eligible: usize,
    pub(super) joint_move_letter_pairs_evaluated: usize,
    pub(super) joint_move_pair_evaluations_min: usize,
    pub(super) joint_move_pair_evaluations_max: usize,
    pub(super) triple_move_candidate_evaluations: usize,
    pub(super) triple_move_constraint_evaluations: usize,
    pub(super) triple_move_replay_event_evaluations: usize,
    pub(super) triple_move_total_budget_exhausted: bool,
    pub(super) triple_moves_accepted: usize,
    pub(super) triple_move_prefixes_eligible: usize,
    pub(super) triple_move_prefixes_evaluated: usize,
    pub(super) prefix_cegar_hypotheses_attempted: usize,
    pub(super) prefix_cegar_hypotheses_unsat: usize,
    pub(super) prefix_cegar_hypotheses_capped: usize,
    pub(super) prefix_cegar_models: usize,
    pub(super) prefix_cegar_clauses: usize,
    pub(super) prefix_cegar_replay_event_evaluations: usize,
    pub(super) prefix_cegar_exact_models: usize,
    pub(super) prefix_cegar_core_size_min: usize,
    pub(super) prefix_cegar_core_size_max: usize,
    pub(super) prefix_cegar_total_budget_exhausted: bool,
    pub(super) top_source_hypotheses_retained: usize,
    pub(super) planted_top_source_hypothesis_rank: Option<usize>,
    pub(super) planted_top_source_hypothesis_retained: Option<bool>,
    pub(super) top_source_states_expanded: usize,
    pub(super) top_source_states_pruned: usize,
    pub(super) top_source_states_dropped: usize,
    pub(super) top_source_constraint_evaluations: usize,
    pub(super) top_source_third_symbol_evaluations: usize,
    pub(super) top_source_elapsed: Duration,
    pub(super) exact_candidate_count: usize,
    pub(super) planted_base_recovered: Option<bool>,
    pub(super) observed_letters: Vec<char>,
    pub(super) anchored_letters: Vec<char>,
    pub(super) event_count: usize,
    pub(super) best_mismatches: usize,
    pub(super) best_round_trip: HiddenBaseRoundTrip,
    pub(super) representative_key: Option<HiddenBaseLocalRecoveredKey>,
}
