//! Handler for the hidden-base GAK/deck identifiability audit.

use std::fmt::Write as _;
use std::process::ExitCode;

use noita_eye_puzzle::attack::gak_attack::lymm_deck::{
    HiddenBaseAuditConfig, HiddenBaseAuditReport, HiddenBaseAuditSelfTestReport,
    HiddenBaseControlExpectation, HiddenBaseControlReport, HiddenBaseFixtureConfig,
    HiddenBaseIdentifiabilityStatus, HiddenBaseKind, hidden_base_audit_self_test,
    run_hidden_base_identifiability_audit,
};

use crate::cli::args_gak_hidden_base::{GakHiddenBaseAuditArgs, GakHiddenBaseKind};

macro_rules! appendln {
    ($out:expr, $($arg:tt)*) => {
        writeln!($out, $($arg)*).expect("write to String")
    };
}

/// Dispatches the `gak-hidden-base-audit` subcommand.
pub(crate) fn run_gak_hidden_base_audit(args: &GakHiddenBaseAuditArgs) -> ExitCode {
    let controls = if args.skip_controls {
        None
    } else {
        match hidden_base_audit_self_test(args.seed) {
            Ok(report) if report.passed() => Some(report),
            Ok(report) => {
                print!("{}", render_controls(Some(&report), false));
                eprintln!("gak-hidden-base-audit error: planted controls or matched nulls failed");
                return ExitCode::FAILURE;
            }
            Err(error) => {
                eprintln!("gak-hidden-base-audit control error: {error}");
                return ExitCode::FAILURE;
            }
        }
    };

    let config = HiddenBaseAuditConfig {
        fixture: HiddenBaseFixtureConfig {
            n: args.n,
            pt_alphabet: args
                .pt_alphabet
                .clone()
                .unwrap_or_else(|| default_pt_alphabet(args.n)),
            swap_budget: args.num_swaps,
            message_count: args.messages,
            message_len: args.message_len,
            seed: args.seed,
            base_kind: cli_base_kind(args.base_kind, args.n),
        },
        trials: args.trials,
    };
    let report = match run_hidden_base_identifiability_audit(&config) {
        Ok(report) => report,
        Err(error) => {
            eprintln!("gak-hidden-base-audit error: {error}");
            return ExitCode::FAILURE;
        }
    };

    print!(
        "{}",
        render_audit_report(&report, controls.as_ref(), args.skip_controls)
    );
    if report.passed() {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}

fn default_pt_alphabet(n: usize) -> String {
    let count = n.saturating_sub(1).min(26);
    (0..count)
        .filter_map(|index| {
            u8::try_from(index)
                .ok()
                .and_then(|offset| b'A'.checked_add(offset))
                .map(char::from)
        })
        .collect()
}

fn cli_base_kind(kind: GakHiddenBaseKind, n: usize) -> HiddenBaseKind {
    match kind {
        GakHiddenBaseKind::Random => HiddenBaseKind::Random,
        GakHiddenBaseKind::Affine => HiddenBaseKind::Affine {
            shift: n / 3 + 1,
            decimation: 3,
        },
    }
}

fn render_audit_report(
    report: &HiddenBaseAuditReport,
    controls: Option<&HiddenBaseAuditSelfTestReport>,
    controls_skipped: bool,
) -> String {
    let mut out = String::new();
    let fixture = &report.config.fixture;
    let (min_candidates, max_candidates) = report.base_candidate_range().unwrap_or((0, 0));
    appendln!(
        &mut out,
        "gak-hidden-base-audit: trials={} n={} max-swaps={} messages={}x{} base={}",
        report.trials.len(),
        fixture.n,
        fixture.swap_budget,
        fixture.message_count,
        fixture.message_len,
        fixture.base_kind.label()
    );
    appendln!(
        &mut out,
        "cipher convention: state=compose(perm(L), state); compose(p1,p2)[i]=p2[p1[i]]; emit state[0]; perm(L)=B o sigma_L; sigma_L is generated by <=s top swaps (0,k); identity restart per message"
    );
    appendln!(
        &mut out,
        "plaintext alphabet: {} ({} letters)",
        fixture.pt_alphabet,
        fixture.pt_alphabet.chars().count()
    );
    out.push('\n');
    out.push_str(&render_controls(controls, controls_skipped));
    appendln!(
        &mut out,
        "identifiability: unique={} equivalent-class={} no-candidate={} planted-missing={} round-trip-mismatch={}",
        report.status_count(HiddenBaseIdentifiabilityStatus::PlantedBaseUnique),
        report.status_count(HiddenBaseIdentifiabilityStatus::EquivalentBaseClass),
        report.status_count(HiddenBaseIdentifiabilityStatus::NoCompatibleBase),
        report.status_count(HiddenBaseIdentifiabilityStatus::PlantedBaseMissing),
        report.status_count(HiddenBaseIdentifiabilityStatus::RoundTripMismatch)
    );
    appendln!(
        &mut out,
        "compatible hidden bases per trial: min={} max={} (brute-force base space n!={})",
        min_candidates,
        max_candidates,
        report
            .trials
            .first()
            .and_then(|trial| trial.surface.brute_force_base_count)
            .map_or_else(|| "overflow".to_owned(), |value| value.to_string())
    );
    if let Some(first) = report.trials.first() {
        let surface = &first.surface;
        appendln!(
            &mut out,
            "trial-0 signal: observed={}/{} anchored={} unanchored={} unobserved={}",
            surface.observed_letters.len(),
            fixture.pt_alphabet.chars().count(),
            surface.identity_anchor_letters.len(),
            surface.unanchored_observed_letters.len(),
            format_chars(&surface.unobserved_letters)
        );
        appendln!(
            &mut out,
            "trial-0 decomposition: status={} bases={} sigma-domain={} round-trip={}/{} exact={} variable-off-top-base-positions={} sigma-ambiguous-letters={}",
            surface.status.label(),
            surface.base_candidate_count,
            surface.sigma_domain_size,
            surface.round_trip.matched,
            surface.round_trip.total,
            surface.round_trip.exact,
            surface.variable_off_top_positions.len(),
            format_chars(&surface.sigma_ambiguous_letters)
        );
    }
    out
}

fn render_controls(
    controls: Option<&HiddenBaseAuditSelfTestReport>,
    controls_skipped: bool,
) -> String {
    let mut out = String::new();
    if controls_skipped {
        appendln!(&mut out, "hidden-base controls: SKIPPED by --skip-controls");
        out.push('\n');
        return out;
    }
    let Some(report) = controls else {
        appendln!(&mut out, "hidden-base controls: not run");
        out.push('\n');
        return out;
    };
    appendln!(
        &mut out,
        "hidden-base controls: {}",
        if report.passed() { "PASS" } else { "FAIL" }
    );
    append_control(&mut out, &report.planted_positive);
    append_control(&mut out, &report.random_full_key_null);
    append_control(&mut out, &report.over_budget_low_null);
    append_control(&mut out, &report.over_budget_positive);
    append_control(&mut out, &report.ciphertext_label_shuffle_null);
    out.push('\n');
    out
}

fn append_control(out: &mut String, report: &HiddenBaseControlReport) {
    appendln!(
        out,
        "  {}: {} expected={} accepted={} exact={} bases={} status={}",
        report.name,
        if report.passed() { "PASS" } else { "FAIL" },
        expectation_label(report.expectation),
        report.accepted,
        report.exact_round_trip,
        report.base_candidate_count,
        report.status.label()
    );
}

fn expectation_label(expectation: HiddenBaseControlExpectation) -> &'static str {
    match expectation {
        HiddenBaseControlExpectation::Accept => "accept",
        HiddenBaseControlExpectation::Reject => "reject",
    }
}

fn format_chars(chars: &[char]) -> String {
    if chars.is_empty() {
        "none".to_owned()
    } else {
        chars.iter().collect()
    }
}
