//! Hidden-base fixture generation and identifiability audit for Lymm deck keys.
//!
//! This module does not recover a key from ciphertext. It measures the
//! decomposition surface after a supplied mapping has already passed exact
//! re-encryption: how many hidden bases `B` can explain the observed per-letter
//! permutations as `perm(L) = B o sigma_L`, where each `sigma_L` is generated by
//! bounded top-card swaps.

use std::collections::{BTreeMap, BTreeSet};

use crate::ciphers::validate_permutation;
use crate::nulls::null::mix_seed;

use super::{
    KnownPlaintextPair, LymmDeckError, LymmDeckSpec, PlantedLymmMapping, TopSwapConstraints,
    compose_lymm, encrypt_lymm_deck, enumerate_top_swap_domains, plant_hidden_base_fixture,
};

const TRIAL_SEED_TAG: u64 = 0x6862_7472_6961_6c05;

/// Default deterministic seed for hidden-base fixture audits.
pub const DEFAULT_HIDDEN_BASE_AUDIT_SEED: u64 = 0x6761_6b5f_6862_3031;

/// Hidden-base family used by a planted fixture.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum HiddenBaseKind {
    /// Uniform random permutation of `0..n`, generated by in-crate `SplitMix64`.
    Random,
    /// Structured affine base built with Lymm's shift/decimation constructor.
    Affine {
        /// Rotation shift.
        shift: usize,
        /// Multiplicative decimation.
        decimation: usize,
    },
}

impl HiddenBaseKind {
    /// Short report label for this base family.
    #[must_use]
    pub fn label(&self) -> String {
        match self {
            Self::Random => "random".to_owned(),
            Self::Affine { shift, decimation } => {
                format!("affine:shift={shift},decimation={decimation}")
            }
        }
    }
}

/// Configuration for one deterministic hidden-base fixture.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HiddenBaseFixtureConfig {
    /// Deck size.
    pub n: usize,
    /// Plaintext alphabet in key order.
    pub pt_alphabet: String,
    /// Maximum top-card swap budget used to plant each `sigma_L`.
    pub swap_budget: usize,
    /// Number of independent identity-restart messages.
    pub message_count: usize,
    /// Plaintext alphabet characters per message.
    pub message_len: usize,
    /// Seed controlling base, mapping, and plaintext generation.
    pub seed: u64,
    /// Hidden-base construction family.
    pub base_kind: HiddenBaseKind,
}

/// A planted hidden-base known-plaintext fixture.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HiddenBaseFixture {
    /// Complete Lymm deck spec containing the planted hidden base.
    pub spec: LymmDeckSpec,
    /// Planted per-letter mapping and top-swap words.
    pub planted: PlantedLymmMapping,
    /// Identity-restart known-plaintext/ciphertext pairs under the planted key.
    pub pairs: Vec<KnownPlaintextPair>,
    /// Fixture configuration used to generate this instance.
    pub config: HiddenBaseFixtureConfig,
}

/// Configuration for a multi-trial identifiability audit.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HiddenBaseAuditConfig {
    /// Base fixture shape. The seed is mixed with the trial index.
    pub fixture: HiddenBaseFixtureConfig,
    /// Number of deterministic fixtures to sample.
    pub trials: usize,
}

/// Exact re-encryption check for an audited mapping.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HiddenBaseRoundTrip {
    /// Matching ciphertext character positions.
    pub matched: usize,
    /// Total ciphertext character positions compared.
    pub total: usize,
    /// Whether every ciphertext byte matched exactly.
    pub exact: bool,
}

/// Hidden-base decomposition status for one mapping surface.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HiddenBaseIdentifiabilityStatus {
    /// The planted base is the only compatible hidden base.
    PlantedBaseUnique,
    /// The planted base is one member of a larger compatible class.
    EquivalentBaseClass,
    /// No hidden base in the bounded top-swap model explains the mapping.
    NoCompatibleBase,
    /// Compatible bases exist but do not include the planted base.
    PlantedBaseMissing,
    /// The supplied mapping does not re-encrypt the known plaintext exactly.
    RoundTripMismatch,
}

impl HiddenBaseIdentifiabilityStatus {
    /// Stable report label.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::PlantedBaseUnique => "planted-base-unique",
            Self::EquivalentBaseClass => "equivalent-base-class",
            Self::NoCompatibleBase => "no-compatible-base",
            Self::PlantedBaseMissing => "planted-base-missing",
            Self::RoundTripMismatch => "round-trip-mismatch",
        }
    }
}

/// Identifiability report for one supplied mapping and known-plaintext corpus.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HiddenBaseSurfaceReport {
    /// Deck size.
    pub n: usize,
    /// Top-swap budget used by the decomposition audit.
    pub max_swaps: usize,
    /// Number of de-duplicated `sigma` candidates at this budget.
    pub sigma_domain_size: usize,
    /// `n!` brute-force hidden-base count when it fits in `u128`.
    pub brute_force_base_count: Option<u128>,
    /// Number of compatible hidden bases after intersecting observed letters.
    pub base_candidate_count: usize,
    /// Whether the planted base is among the compatible bases, when known.
    pub planted_base_in_candidates: Option<bool>,
    /// Exact re-encryption result for the supplied mapping.
    pub round_trip: HiddenBaseRoundTrip,
    /// Aggregate status.
    pub status: HiddenBaseIdentifiabilityStatus,
    /// Plaintext letters that appear at least once.
    pub observed_letters: Vec<char>,
    /// Plaintext letters absent from the known-plaintext corpus.
    pub unobserved_letters: Vec<char>,
    /// Plaintext letters seen in identity-restart first position.
    pub identity_anchor_letters: Vec<char>,
    /// Observed letters without an identity-restart top anchor.
    pub unanchored_observed_letters: Vec<char>,
    /// Base positions fixed across all compatible hidden bases.
    pub fixed_base_positions: Vec<usize>,
    /// Base positions that vary across compatible hidden bases.
    pub variable_base_positions: Vec<usize>,
    /// Nonzero base positions that vary across compatible hidden bases.
    pub variable_off_top_positions: Vec<usize>,
    /// Observed letters with more than one compatible `sigma_L`.
    pub sigma_ambiguous_letters: Vec<char>,
    /// Largest compatible `sigma_L` count seen for one observed letter.
    pub max_sigma_candidates_for_letter: usize,
}

impl HiddenBaseSurfaceReport {
    /// Returns true only when exact re-encryption holds and the planted base, if
    /// supplied, remains in a non-empty compatible class.
    #[must_use]
    pub fn accepted(&self) -> bool {
        self.round_trip.exact
            && self.base_candidate_count > 0
            && self.planted_base_in_candidates != Some(false)
    }
}

/// One deterministic fixture trial in an aggregate audit.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HiddenBaseTrialReport {
    /// Trial index.
    pub trial_index: usize,
    /// Mixed seed used for this trial.
    pub seed: u64,
    /// Surface report for this trial.
    pub surface: HiddenBaseSurfaceReport,
}

/// Aggregate identifiability audit across deterministic planted fixtures.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HiddenBaseAuditReport {
    /// Configuration used for the audit.
    pub config: HiddenBaseAuditConfig,
    /// Per-trial reports.
    pub trials: Vec<HiddenBaseTrialReport>,
}

impl HiddenBaseAuditReport {
    /// Count trials with the requested status.
    #[must_use]
    pub fn status_count(&self, status: HiddenBaseIdentifiabilityStatus) -> usize {
        self.trials
            .iter()
            .filter(|trial| trial.surface.status == status)
            .count()
    }

    /// Returns true when every planted trial re-encrypts exactly and retains its
    /// planted base in the compatible class.
    #[must_use]
    pub fn passed(&self) -> bool {
        self.trials
            .iter()
            .all(|trial| trial.surface.accepted() && trial.surface.round_trip.exact)
    }

    /// Minimum and maximum compatible-base counts across trials.
    #[must_use]
    pub fn base_candidate_range(&self) -> Option<(usize, usize)> {
        let mut iter = self
            .trials
            .iter()
            .map(|trial| trial.surface.base_candidate_count);
        let first = iter.next()?;
        let mut min_value = first;
        let mut max_value = first;
        for value in iter {
            min_value = min_value.min(value);
            max_value = max_value.max(value);
        }
        Some((min_value, max_value))
    }
}

/// Runs the aggregate hidden-base identifiability audit.
///
/// # Errors
/// Returns [`LymmDeckError`] if any fixture cannot be planted or audited.
pub fn run_hidden_base_identifiability_audit(
    config: &HiddenBaseAuditConfig,
) -> Result<HiddenBaseAuditReport, LymmDeckError> {
    if config.trials == 0 {
        return Err(LymmDeckError::HiddenBaseConfig {
            reason: "trials must be at least one",
        });
    }
    let mut trials = Vec::with_capacity(config.trials);
    for trial_index in 0..config.trials {
        let mut fixture_config = config.fixture.clone();
        fixture_config.seed = mix_seed(
            config.fixture.seed,
            TRIAL_SEED_TAG ^ u64::try_from(trial_index).unwrap_or(0),
        );
        let fixture = plant_hidden_base_fixture(&fixture_config)?;
        let surface = audit_hidden_base_mapping(
            &fixture.spec,
            &fixture.pairs,
            &fixture.planted.pt_mapping,
            fixture_config.swap_budget,
            Some(&fixture.spec.base),
        )?;
        trials.push(HiddenBaseTrialReport {
            trial_index,
            seed: fixture_config.seed,
            surface,
        });
    }
    Ok(HiddenBaseAuditReport {
        config: config.clone(),
        trials,
    })
}

/// Audits one supplied mapping against known plaintext and a bounded hidden-base
/// decomposition surface.
///
/// # Errors
/// Returns [`LymmDeckError`] if the mapping is invalid or the top-swap domain
/// cannot be enumerated.
pub fn audit_hidden_base_mapping(
    spec: &LymmDeckSpec,
    pairs: &[KnownPlaintextPair],
    pt_mapping: &BTreeMap<char, Vec<usize>>,
    max_swaps: usize,
    planted_base: Option<&[usize]>,
) -> Result<HiddenBaseSurfaceReport, LymmDeckError> {
    validate_mapping_permutations(spec, pt_mapping)?;
    if let Some(base) = planted_base {
        validate_permutation("hidden-base planted base", base, spec.n)?;
    }
    let round_trip = exact_round_trip(spec, pairs, pt_mapping)?;
    let domains = enumerate_top_swap_domains(spec, &TopSwapConstraints::up_to(max_swaps))?;
    let sigma_inverses = domains
        .candidates
        .iter()
        .map(|candidate| invert_permutation(&candidate.sigma_permutation(spec.n)))
        .collect::<Vec<_>>();
    let sigma_set = domains
        .candidates
        .iter()
        .map(|candidate| candidate.sigma_permutation(spec.n))
        .collect::<BTreeSet<_>>();

    let signal = plaintext_signal(spec, pairs);
    let candidate_bases =
        compatible_bases_for_observed_letters(&signal.observed, pt_mapping, &sigma_inverses)?;
    let planted_base_in_candidates = planted_base.map(|base| candidate_bases.contains(base));
    let (fixed_base_positions, variable_base_positions) =
        base_position_variability(spec.n, &candidate_bases);
    let variable_off_top_positions = variable_base_positions
        .iter()
        .copied()
        .filter(|&position| position != spec.emit_index)
        .collect::<Vec<_>>();
    let (sigma_ambiguous_letters, max_sigma_candidates_for_letter) = sigma_ambiguity(
        spec,
        &signal.observed,
        pt_mapping,
        &candidate_bases,
        &sigma_set,
    );
    let status = surface_status(
        round_trip.exact,
        candidate_bases.len(),
        planted_base_in_candidates,
    );

    Ok(HiddenBaseSurfaceReport {
        n: spec.n,
        max_swaps,
        sigma_domain_size: domains.candidates.len(),
        brute_force_base_count: factorial_u128(spec.n),
        base_candidate_count: candidate_bases.len(),
        planted_base_in_candidates,
        round_trip,
        status,
        observed_letters: signal.observed,
        unobserved_letters: signal.unobserved,
        identity_anchor_letters: signal.identity_anchors,
        unanchored_observed_letters: signal.unanchored_observed,
        fixed_base_positions,
        variable_base_positions,
        variable_off_top_positions,
        sigma_ambiguous_letters,
        max_sigma_candidates_for_letter,
    })
}

fn validate_mapping_permutations(
    spec: &LymmDeckSpec,
    pt_mapping: &BTreeMap<char, Vec<usize>>,
) -> Result<(), LymmDeckError> {
    for &letter in &spec.pt_alphabet {
        let perm = pt_mapping
            .get(&letter)
            .ok_or(LymmDeckError::MissingPlaintextMapping { letter })?;
        validate_permutation("hidden-base mapping", perm, spec.n)?;
    }
    Ok(())
}

fn exact_round_trip(
    spec: &LymmDeckSpec,
    pairs: &[KnownPlaintextPair],
    pt_mapping: &BTreeMap<char, Vec<usize>>,
) -> Result<HiddenBaseRoundTrip, LymmDeckError> {
    let mut matched = 0usize;
    let mut total = 0usize;
    let mut exact = true;
    for pair in pairs {
        let encrypted = encrypt_lymm_deck(spec, pt_mapping, &pair.plaintext)?;
        let expected = pair.ciphertext.chars().collect::<Vec<_>>();
        let actual = encrypted.chars().collect::<Vec<_>>();
        total = total.saturating_add(expected.len().max(actual.len()));
        matched = matched.saturating_add(
            expected
                .iter()
                .zip(&actual)
                .filter(|(left, right)| left == right)
                .count(),
        );
        exact &= expected == actual;
    }
    Ok(HiddenBaseRoundTrip {
        matched,
        total,
        exact,
    })
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct PlaintextSignal {
    observed: Vec<char>,
    unobserved: Vec<char>,
    identity_anchors: Vec<char>,
    unanchored_observed: Vec<char>,
}

fn plaintext_signal(spec: &LymmDeckSpec, pairs: &[KnownPlaintextPair]) -> PlaintextSignal {
    let mut observed = BTreeSet::new();
    let mut anchors = BTreeSet::new();
    for pair in pairs {
        let mut first_plaintext = None;
        for ch in pair.plaintext.chars() {
            if spec.is_plaintext_char(ch) {
                let _inserted = observed.insert(ch);
                if first_plaintext.is_none() {
                    first_plaintext = Some(ch);
                }
            }
        }
        if let Some(ch) = first_plaintext {
            let _inserted = anchors.insert(ch);
        }
    }
    let observed_letters = ordered_letters(&spec.pt_alphabet, &observed);
    let identity_anchors = ordered_letters(&spec.pt_alphabet, &anchors);
    let unobserved = spec
        .pt_alphabet
        .iter()
        .copied()
        .filter(|letter| !observed.contains(letter))
        .collect::<BTreeSet<_>>();
    let unobserved_letters = ordered_letters(&spec.pt_alphabet, &unobserved);
    let unanchored = observed
        .iter()
        .copied()
        .filter(|letter| !anchors.contains(letter))
        .collect::<BTreeSet<_>>();
    let unanchored_observed = ordered_letters(&spec.pt_alphabet, &unanchored);
    PlaintextSignal {
        observed: observed_letters,
        unobserved: unobserved_letters,
        identity_anchors,
        unanchored_observed,
    }
}

fn ordered_letters(order: &[char], letters: &BTreeSet<char>) -> Vec<char> {
    order
        .iter()
        .copied()
        .filter(|letter| letters.contains(letter))
        .collect()
}

fn compatible_bases_for_observed_letters(
    observed_letters: &[char],
    pt_mapping: &BTreeMap<char, Vec<usize>>,
    sigma_inverses: &[Vec<usize>],
) -> Result<BTreeSet<Vec<usize>>, LymmDeckError> {
    let mut candidates: Option<BTreeSet<Vec<usize>>> = None;
    for &letter in observed_letters {
        let Some(perm) = pt_mapping.get(&letter) else {
            return Err(LymmDeckError::MissingPlaintextMapping { letter });
        };
        let mut letter_bases = BTreeSet::new();
        for sigma_inverse in sigma_inverses {
            let base = compose_lymm(sigma_inverse, perm)?;
            let _inserted = letter_bases.insert(base);
        }
        candidates = Some(match candidates {
            None => letter_bases,
            Some(previous) => previous
                .intersection(&letter_bases)
                .cloned()
                .collect::<BTreeSet<_>>(),
        });
    }
    Ok(candidates.unwrap_or_default())
}

fn base_position_variability(
    n: usize,
    candidates: &BTreeSet<Vec<usize>>,
) -> (Vec<usize>, Vec<usize>) {
    if candidates.is_empty() {
        return (Vec::new(), (0..n).collect());
    }
    let mut fixed = Vec::new();
    let mut variable = Vec::new();
    for position in 0..n {
        let mut values = candidates
            .iter()
            .filter_map(|base| base.get(position).copied());
        let Some(first) = values.next() else {
            variable.push(position);
            continue;
        };
        if values.all(|value| value == first) {
            fixed.push(position);
        } else {
            variable.push(position);
        }
    }
    (fixed, variable)
}

fn sigma_ambiguity(
    spec: &LymmDeckSpec,
    observed_letters: &[char],
    pt_mapping: &BTreeMap<char, Vec<usize>>,
    candidate_bases: &BTreeSet<Vec<usize>>,
    sigma_set: &BTreeSet<Vec<usize>>,
) -> (Vec<char>, usize) {
    let mut ambiguous = Vec::new();
    let mut max_count = 0usize;
    for &letter in observed_letters {
        let Some(perm) = pt_mapping.get(&letter) else {
            continue;
        };
        let mut sigmas = BTreeSet::new();
        for base in candidate_bases {
            let inverse_base = invert_permutation(base);
            let sigma = derive_sigma(&inverse_base, perm);
            if sigma.len() == spec.n && sigma_set.contains(&sigma) {
                let _inserted = sigmas.insert(sigma);
            }
        }
        max_count = max_count.max(sigmas.len());
        if sigmas.len() > 1 {
            ambiguous.push(letter);
        }
    }
    (ambiguous, max_count)
}

fn surface_status(
    exact_round_trip: bool,
    base_candidate_count: usize,
    planted_base_in_candidates: Option<bool>,
) -> HiddenBaseIdentifiabilityStatus {
    if !exact_round_trip {
        return HiddenBaseIdentifiabilityStatus::RoundTripMismatch;
    }
    if base_candidate_count == 0 {
        return HiddenBaseIdentifiabilityStatus::NoCompatibleBase;
    }
    if planted_base_in_candidates == Some(false) {
        return HiddenBaseIdentifiabilityStatus::PlantedBaseMissing;
    }
    if base_candidate_count == 1 {
        HiddenBaseIdentifiabilityStatus::PlantedBaseUnique
    } else {
        HiddenBaseIdentifiabilityStatus::EquivalentBaseClass
    }
}

fn invert_permutation(perm: &[usize]) -> Vec<usize> {
    let mut inverse = vec![0usize; perm.len()];
    for (position, &image) in perm.iter().enumerate() {
        if let Some(slot) = inverse.get_mut(image) {
            *slot = position;
        }
    }
    inverse
}

fn derive_sigma(inverse_base: &[usize], perm: &[usize]) -> Vec<usize> {
    perm.iter()
        .filter_map(|&image| inverse_base.get(image).copied())
        .collect()
}

fn factorial_u128(n: usize) -> Option<u128> {
    let mut value = 1u128;
    for factor in 2..=n {
        value = value.checked_mul(u128::try_from(factor).ok()?)?;
    }
    Some(value)
}
